name: docker_build

on: push

jobs:
    build-to-docker:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Azure Login
        uses: Azure/login@v2.1.0
        with:
          client-id: ${{ secrets.CLIENT_ID }}
          tenant-id: ${{ secrets.TEN_ID }}
          subscription-id: ${{ secrets.SUB_ID }}
          
      - name: Azure Container Registry Login
        uses: Azure/docker-login@v1
        with:
            username: ${{ secrets.ACR_USERNAME }}
            password: ${{ secrets.ACR_PASS }}
            login-server: dockercr01.azurecr.io

      - name: build_image
        run: |
                docker build -t nodeapp .
                docker tag nodeapp:latest dockercr01.azurecr.io/dockerimg:v1
                docker push dockercr01.azurecr.io/dockerimg:v1

    
