name: docker_build

on: push

jobs:
    build-to-docker:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Docker Login
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ USERNAME }}
          password: ${{ PASSWORD }}

      - name: build_image
        run: |
              docker build -t jscriptapp .
              docker tag lakulos/nodeapprepo:nodeapp jscriptapp
              docker push lakulos/nodeapprepo:nodeapp

    
