name: docker_build

on: push

jobs:
    build-to-docker:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Azure Login
        uses: Azure/login@v2.1.0
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          client-id: a9d4b7d1-af8d-47dc-b1ff-cbcd21112360
          tenant-id: 44e0fe4b-405f-4678-bcb4-a6063b67f6b3
          subscription-id: 7f112840-74e8-45d2-8eb8-4d4f4248f2ca
          auth-type: SERVICE_PRINCIPLE
          
      - name: Azure Container Registry Login
        uses: Azure/docker-login@v1
        with:
            username: ${{ secrets.ACR_USERNAME }}
            password: ${{ secrets.ACR_PASS }}
            login-server: dockercr01.azurecr.io

      - name: build_image
        run: |
                docker build -t nodeapp .
                docker tag nodeapp:latest dockercr01.azurecr.io/dockerimg:v1
                docker push dockercr01.azurecr.io/dockerimg:v1

    
