name: docker_build_VM

on: workflow_dispatch

jobs:
    SSH-to-azureVM:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.AZURE_VM_SSH_PRIVATE_KEY }}

      - name: login to Azure VM
        run: ssh -o StrictHostKeyChecking=no ${{ secrets.AZURE_VM_USERNAME }}@${{ secrets.AZURE_VM_IP }} << EOF


    pull-from-docker:
      runs-on: ubuntu-latest
      needs:  
           SSH-to-azureVM
      steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Docker Login
        uses: docker/login-action@v3.3.0
        with:
            username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
            password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

      - name: docker pull
        run: |
              sudo docker pull lakulos/nodeapprepo:jscriptimg
              sudo docker run -d --name node-conntainer -p 4000:4000 lakulos/nodeapprepo:jscriptimg
              EOF
